### ISSUE TITLE
[Component] Filterable, Searchable Table

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#17]
**Objective:** To create data visualization component to be displayed on the tracker landing page, state and county level pages

**Requirements:**
- [Landing Page] User should be able to toggle desired view (States only, Counties only, State + Counties)
- User should be able to search and see filtered down search results in table component
- User should be able to sort by Lawsuits & Default judgments
- Table should include reference copy that provides context for interpreting the meaning of "Default Judgments" 

**Remaining Tasks:**
- [ ] add "show all" button when table is in "counties" or "tracts" view.  clicking will load all available counties / tracts
- [ ] make entire row clickable, in addition to the "view report" button

**Acceptance Criteria: **
- [ ] Component has all functionality mentioned in the requirements
- [ ] Component has been integrated into the Tracker Landing Page, state and county pages

**Comment by Lane** [comment]
additional functional requirement:

- [ ] add "show all" link when limiting the top counties / tracts on the state / county pages so the user can see all counties/tracts in case they don't quite know what they're looking
