### ISSUE TITLE
[Style & CMS] Homepage

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#29]
**Objective:** To apply client approved styling to the homepage, add CMS fields as needed for content on the page

**Tasks:**
- [ ] Apply styles and content based on mockups, mobile -> desktop (need client approval of mockup)
- [ ] Add CMS fields for content

**Comment by Lane** [comment]
made some guesses on mobile -> desktop styling here as well, ready for internal review
