### ISSUE TITLE
"Jump to Map" Implementation

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#71]
## Objective
Implement designs created in [this design ticket ](https://app.zenhub.com/workspaces/dcl-606e62490df4b300151b6a08/issues/hyperobjekt/debt-collection-lab/70)for "jump to map" feature. 

## Resources
[Designs](https://www.figma.com/file/KQ2rcphJF5jniyOn7PoKpg/DCL%3A-Debt-Collection-Lab?node-id=1272%3A237)

Requirements and additional details can be found in the high level ["jump to map" epic](https://app.zenhub.com/workspaces/dcl-606e62490df4b300151b6a08/issues/hyperobjekt/debt-collection-lab/68).

**Comment by Lane** [comment]
# Technical Spec

- add an `onJumpToMap` prop to `TableSection` component (`/src/lawsuit-tracker/sections`) that accepts a callback function
  - when an `onJumpToMap` function is provided to the component, display the "Jump to Map" button to the left of the "View Report" button, and trigger the `onJumpToMap` function with the corresponding location as an argument when clicked.
- add a `activeLocation` prop to `<LawsuitsMapSection />` (`/src/lawsuit-tracker/sections/lawsuits-map.js`).  pass this prop all the way down to `<ChoroplethMap />`
  - add the `activeLocation` prop to `<ChoroplethMap />` (`/src/lawsuit-tracker/map/ChoroplethMap.js`) and when it is set add the highlighted state + details overlay for the corresponding location (see mockup).  use the `activeLocation` data to find the geojson feature in `data.features`, then find the pixel coordinates from the feature using the [project function](https://docs.mapbox.com/mapbox-gl-js/api/map/?size=n_10_n#map#project).  (`mapRef.current.getMap().project([lng, lat])`)
- on the subpage layout component that is used for county and state pages (`/src/lawsuit-tracker/layouts/subpage.js`):
  - add local state that tracks the "jumped to" location (e.g. `const [jumpedLocation, setJumpedLocaton] = useState(null)`)
  - add a `handleJumpToMap` function  that does the following:
    - sets the corresponding location in the local state for the page (`setJumpedLocation`)
    - sets the location hash to the map section (`location.hash = "#map"`), triggering a scroll up to the map
  - add the `onJumpToMap` prop on the `<TableSection />` component to `handleJumpToMap`
  - add the `activeLocation` prop on the `<LawsuitsMapSection />`
