### ISSUE TITLE
Data Evaluation & Target Structure Documentation

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#9]
**Objective:** To determine and document the target data format needed to support visualizations. 
- Review raw data files provided by January Advisors
- Document desired structure
- TBD on who will complete the data transformation (client or Hyperobjekt)

**Acceptance Criteria**
- [x] Target data format documented
- [ ] Estimate provided for effort required to complete transformation on our end

**Comment by Lane** [comment]
i've created some documentation around the [data formats we need for the debt collection tracker](https://docs.google.com/spreadsheets/d/1A6sc28r3tLKcnWK9Pig3ukdahQvHtN4wEDhVokVrSEw/edit#gid=571007233), as well as the [steps needed to take the data they have provided and shape it into the required format](https://drive.google.com/file/d/1ikeY290F8jWBv_Qp0kcwkvs0I-e_W8U_/view?usp=sharing).

there is some significant work required to shape this data into the formats we need.  on top of shaping the data, it needs to be cleaned, aggregated, and in the case of harris county it looks like it needs to be geolocated to map addresses to census tracts.  not sure if this is something that january advisors is planning to take on, or if they are expecting us to do.

if they are hoping we will do this, we'll need additional resources and likely hire someone with a stronger data science background.  i'm not familiar enough with taking on these tasks to create an estimate.
